apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  labels:
    function.knative.dev: "true"
    function.knative.dev/name: app
    function.knative.dev/runtime: go
  name: app
spec:
  template:
    metadata:
      labels:
        function.knative.dev: "true"
        function.knative.dev/name: app
        function.knative.dev/runtime: go
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BUILT
          value: 20220924T112015
        image: docker.io/salaboy/app@sha256:c1b036b2b118bd50e29e537b6b3a79a91f423811e767f0268fb225590caee58f
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
