apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  labels:
    function.knative.dev: "true"
    function.knative.dev/name: kubecon
    function.knative.dev/runtime: go
  name: kubecon
spec:
  template:
    metadata:
      labels:
        function.knative.dev: "true"
        function.knative.dev/name: kubecon
        function.knative.dev/runtime: go
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BUILT
          value: 20220924T112015
        image: docker.io/salaboy/rainbows-to-tshirt@sha256:b55132a2f5ed9c98e78157426d502cb9e41ee4823d7bff01df64860e3c389fa2
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
