apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  labels:
    function.knative.dev: "true"
    function.knative.dev/name: kubecon
    function.knative.dev/runtime: go
  name: kubecon
spec:
  template:
    metadata:
      labels:
        function.knative.dev: "true"
        function.knative.dev/name: kubecon
        function.knative.dev/runtime: go
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BUILT
          value: 20220924T112015
        image: docker.io/salaboy/kubecon@sha256:f7637cc62d8030295930fb866eaf24cfba36a2098ef84107370a1e4aaab5b9ae
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
