apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  labels:
    function.knative.dev: "true"
    function.knative.dev/name: spiderize
    function.knative.dev/runtime: go
  name: spiderize
spec:
  template:
    metadata:
      labels:
        function.knative.dev: "true"
        function.knative.dev/name: spiderize
        function.knative.dev/runtime: go
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: BUILT
          value: 20220924T112015
        image: docker.io/salaboy/spiderize@sha256:b4afe88f742b1e2dafce9391be8430959d7205be306ee250686f5a1fe8b8369c
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        name: user-container
        readinessProbe:
          httpGet:
            path: /health/liveness
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
